//! Load the test certificates generated by `testdata/generate.sh`.
//!
//! These are TEST certificates. They exist so we can write deterministic
//! unit tests against a known PKI hierarchy:
//!
//! ```text
//! root-ca.crt          self-signed root (CA:TRUE, pathlen:2)
//!   └─ inter-ca.crt    intermediate (CA:TRUE, pathlen:0)
//!        └─ leaf.crt   signer (CA:FALSE, digitalSignature)
//! ```

use der::DecodePem;
use std::path::{Path, PathBuf};
use x509_cert::Certificate;

/// Errors from loading or parsing test certificates.
#[derive(Debug, thiserror::Error)]
pub enum TestkitError {
    #[error("could not read {path}: {source}")]
    Read {
        path: String,
        #[source]
        source: std::io::Error,
    },

    #[error("could not parse PEM in {path}: {source}")]
    ParsePem {
        path: String,
        #[source]
        source: der::Error,
    },
}

/// Absolute path to the testdata directory.
///
/// Uses `CARGO_MANIFEST_DIR`, which Cargo sets to the crate's root when
/// running tests. That makes the path independent of the current working
/// directory.
pub fn testdata_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("testdata")
}

/// Load a certificate from `testdata/<name>`.
///
/// `<name>` should include the extension, e.g. `"leaf.crt"`.
pub fn load_cert(name: &str) -> Result<Certificate, TestkitError> {
    let path = testdata_dir().join(name);
    load_cert_from(&path)
}

/// Load a certificate from an arbitrary path.
pub fn load_cert_from(path: &Path) -> Result<Certificate, TestkitError> {
    let bytes = std::fs::read(path).map_err(|source| TestkitError::Read {
        path: path.display().to_string(),
        source,
    })?;

    let text = String::from_utf8_lossy(&bytes);
    Certificate::from_pem(text.as_ref()).map_err(|source| TestkitError::ParsePem {
        path: path.display().to_string(),
        source,
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn loads_root_ca() {
        let cert = load_cert("root-ca.crt").expect("load root-ca.crt");
        let cn = subject_cn(&cert);
        assert_eq!(cn, "CertiLens Test Root CA");
    }

    #[test]
    fn loads_intermediate_ca() {
        let cert = load_cert("inter-ca.crt").expect("load inter-ca.crt");
        assert_eq!(subject_cn(&cert), "CertiLens Test Intermediate CA");
    }

    #[test]
    fn loads_leaf() {
        let cert = load_cert("leaf.crt").expect("load leaf.crt");
        assert_eq!(subject_cn(&cert), "CertiLens Test Signer");
    }

    #[test]
    fn root_is_self_signed() {
        let cert = load_cert("root-ca.crt").expect("load root-ca.crt");
        assert_eq!(
            cert.tbs_certificate.subject, cert.tbs_certificate.issuer,
            "root CA's subject should equal its issuer"
        );
    }

    #[test]
    fn leaf_issuer_matches_intermediate_subject() {
        let leaf = load_cert("leaf.crt").expect("load leaf.crt");
        let inter = load_cert("inter-ca.crt").expect("load inter-ca.crt");
        assert_eq!(
            leaf.tbs_certificate.issuer, inter.tbs_certificate.subject,
            "leaf's issuer should equal intermediate's subject"
        );
    }

    /// Extract the CN from a certificate's subject.
    fn subject_cn(cert: &Certificate) -> String {
        // Subject is a Name, which is a Vec of RDN sets. Each RDN set is
        // a Vec of AttributeTypeAndValue. We walk it looking for CN.
        const OID_CN: &str = "2.5.4.3";
        for rdn in cert.tbs_certificate.subject.0.iter() {
            for atv in rdn.0.iter() {
                if atv.oid.to_string() == OID_CN {
                    // The value is an ASN.1 string; decode as UTF-8.
                    if let Ok(s) = atv.value.decode_as::<der::asn1::Utf8StringRef>() {
                        return s.as_str().to_string();
                    }
                    // Fallback: raw bytes as lossy UTF-8.
                    return String::from_utf8_lossy(atv.value.value()).into_owned();
                }
            }
        }
        String::new()
    }
}
