[package]
name = "certilens-python"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
# A "cdylib" is a shared library that Python can import.
crate-type = ["cdylib"]

[dependencies]
certilens-core = { path = "../certilens-core" }
certilens-pdf = { path = "../certilens-pdf"}
certilens-crypto = { path = "../certilens-crypto" }
pyo3.workspace = true
serde_json.workspace = true
